name: Staging to Ducktrio ACR
on:
  push:
    branches:
      - main
env:
  ACR_LOGIN_SERVER: ${{secrets.ACR_LOGIN_SERVER}}
  IMAGE_NAME: ${{secrets.IMAGE_NAME}}
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image and Push to ACR Staging
        run: |
          TAG=${GITHUB_SHA}
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG .
          docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:staging
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:staging
